---
abstract: "Override LWP HTTP/HTTPS request's host like /etc/hosts"
author:
  - 'NAKAGAWA Masaki <masaki@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  LWP::UserAgent: 0
  Test::Fake::HTTPD: 0.04
  Test::More: 0.98
  Test::UseAllModules: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: LWP-UserAgent-DNS-Hosts
no_index:
  directory:
    - inc
    - t
    - xt
recommends:
  HTTP::Daemon::SSL: 0
  LWP::Protocol::https: 0
requires:
  Guard: 0
  LWP::Protocol: 0
  LWP::Protocol::http: 0
  parent: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/masaki/p5-LWP-UserAgent-DNS-Hosts.git
version: 0.04
